version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: /Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - project_network

  media-server:
    image: nginx:latest
    ports:
      - "8080:80" # Map port 80 in the container to port 8080 on your localhost
    volumes:
      - ./media:/usr/share/nginx/html/media
    networks:
      - project_network

networks:
  project_network:
